monorepo & create-svelte-ux
techniq/svelte-ux pull request #119
Opened 2023-11-09 21:02 UTC by jycouet

2023-11-09 23:13 UTC, techniq requested changes
Quick review while I had a minute.  I'll pull it locally hopefully tonight and kick it around.  I know the Vercel build is failing...

![image](https://github.com/techniq/svelte-ux/assets/177476/95c6e346-736f-479c-8833-e4f24dbb9381)

I'm figuring I can just set the Root Directory to packages/svelte-ux to resolve (or similar).

![image](https://github.com/techniq/svelte-ux/assets/177476/b14d8b6f-e0ca-4af0-a5a6-0ce970df71d7)

2023-11-09 23:13 UTC, techniq commented on packages/create-svelte-ux/bin.js
> +      initialValue: 'react-typescript',
Maybe we call that template `basic` or `barebone` or something too.

2023-11-09 23:13 UTC, techniq commented on packages/create-svelte-ux/package.json
> +    "url": "https://github.com/jycouet/svelte-ux-monorepo",
URL :)

2023-11-09 23:13 UTC, techniq commented on .github/workflows/ci.yml
> +        uses: jycouet/jycouet/shared-config/setup@main
Is it possible to not have this dependency?

2023-11-10 03:56 UTC, techniq commented on .github/workflows/ci.yml
> +        uses: jycouet/jycouet/shared-config/setup@main
:) 
![image](https://github.com/techniq/svelte-ux/assets/177476/e3b2061e-df46-4cfa-80ea-1f27d2174019)

2023-11-10 04:06 UTC, techniq commented
> Quick review while I had a minute. I'll pull it locally hopefully tonight and kick it around. I know the Vercel build is failing...
> 
> ![image](https://user-images.githubusercontent.com/177476/281907745-95c6e346-736f-479c-8833-e4f24dbb9381.png)
> 
> I'm figuring I can just set the Root Directory to packages/svelte-ux to resolve (or similar).
> 
> ![image](https://user-images.githubusercontent.com/177476/281907853-b14d8b6f-e0ca-4af0-a5a6-0ce970df71d7.png)

build fixed

![image](https://github.com/techniq/svelte-ux/assets/177476/962349cd-1542-4ed5-9956-ac92bc836516)

2023-11-10 07:17 UTC, jycouet commented on packages/create-svelte-ux/bin.js
> +console.log(`${gray(`create-svelte-ux version ${version}`)}\n`);
Yes, it's before I did the monorepo 😅
I will do it now

2023-11-10 17:05 UTC, techniq approved these changes

2023-11-10 17:06 UTC, merged